[package]
name = "ssh-keys"
version = "0.1.0"
authors = ["mister_person <mister.person@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.6"
enigo = "0.0.14"
